--
SELECT FILM_ID,
	CATEGORY_ID
FROM FILM_CATEGORY
NATURAL JOIN
	(SELECT NAME,
			CATEGORY_ID
		FROM CATEGORY);
--
SELECT FILM_ID, CATEGORY_ID
FROM FILM_CATEGORY
NATURAL JOIN
(SELECT NAME, CATEGORY_ID
 FROM CATEGORY) AS subquery_alias;
 
-- subquery
SELECT CUSTOMER_ID,
	FIRST_NAME,
	LAST_NAME
FROM CUSTOMER
WHERE CUSTOMER_ID IN
		(SELECT CUSTOMER_ID
			FROM RENTAL
			WHERE RETURN_DATE IS NULL );

--
SELECT AVG(RENTAL_COUNT)
FROM
	(SELECT CUSTOMER_ID,
			COUNT(*) AS RENTAL_COUNT
		FROM RENTAL
		GROUP BY CUSTOMER_ID) AS AVG_RENTAL_COUNTS;
	
--
SELECT AVG(RENTAL_COUNT)
FROM
	(SELECT CUSTOMER_ID,
			COUNT(CUSTOMER_ID) AS RENTAL_COUNT
		FROM RENTAL
		GROUP BY CUSTOMER_ID) AS AVG_RENTAL_COUNTS;
--
SELECT avg(rental_count)
FROM (
    SELECT customer_id, COUNT(*) AS rental_count
    FROM rental
    GROUP BY customer_id
) AS avg_rental_counts;

--
SELECT CUSTOMER.CUSTOMER_ID,
	CUSTOMER.FIRST_NAME,
	COUNT(RENTAL.CUSTOMER_ID) AS RENTAL_COUNT
FROM CUSTOMER
LEFT JOIN RENTAL ON CUSTOMER.CUSTOMER_ID = RENTAL.CUSTOMER_ID
GROUP BY CUSTOMER.CUSTOMER_ID,
	CUSTOMER.FIRST_NAME;

--
SELECT CORR(AVG(AMOUNT),
EXTRACT(MONTH
FROM PAYMENT_DATE))
FROM PAYMENT
GROUP BY EXTRACT(MONTH
FROM PAYMENT_DATE);

--
SELECT CORR(AMOUNT,
EXTRACT(MONTH
FROM PAYMENT_DATE))
FROM PAYMENT;



